/*ENGINE INTERNALS*/

/*FUNCTIONS*/

/*
drawSprite() //DRAWS SPRITES, USED BY renderingSystem.ts IN `renderingSpriteSystem()`
isEntityBlockingInput() //RETURNS WHETHER AN ENTITY I.E 'Shape' , 'Sprite' ETC BLOCKING A BUTTON
getEntitySize() //RETURNS THE SIZE OF ENTITY COVERING ON SCREEN AS A VECTOR 2 , CHECKS WHETHER ENTITY IS A SCENE
                SPRITE OR SHAPE , THAN GET'S IT'S SIZE. HELPFUL IN `alignmentSystem.ts`
calculateAlignedPosition() //RETURNS THE ALIGNED POSITION OF AN ENTITY , USED IN `alignmentSystem.ts`
isEntityCentered() //RETURNS WHETHER AN ENTITY IS CENTERED OR NOT , USED IN `alignmentSystem.ts`
*/

/*WHAT IS ENGINE INTERNALS*/

/*
`EngineInternals` IS A CLASS THAT CONTAINS CODE WHICH IS USED BY THE ENGINE BUT NOT AVAILABLE TO USER
WE DONT WANT TO MAKE ALL THE FUNCTIONS PUBLIC AS THAT MIGHT BECOME TOO COMPLICATED , 
BUT YOU CAN STILL FREELY CHECK THEM IN THE SOURCE CODE
*/